CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    note_contents TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    folder_id INTEGER
        REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL
);